kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: memcached-operator-instrumented
subjects:
- kind: ServiceAccount
  name: memcached-operator-instrumented
roleRef:
  kind: Role
  name: memcached-operator-instrumented
  apiGroup: rbac.authorization.k8s.io
